RGCN:
  project_name: BIMCompNet_RGCN
  run_name: 'RGCN5000'
  data_dir: 'H:\BIMCompNet'
  save_path: 'Q:\pychem_project\BIMCompNet\results\rgcn_output\test_5000'
  ifc_file_graph_cache: 'Q:\pychem_project\BIMCompNet\data\rgcn_data_cache\c_5000'
  model_weights_path: 'Q:\pychem_project\BIMCompNet\results\rgcn_output\test_5000\f1_rgcn_model.pth'
  isg_name: 'REVERSE_IFCSchemaGraph.bin'
  gpu_device: '0'
  # "sample_100", "sample_500", "sample_1000", "sample_5000"
  sample: "sample_5000"
  model: RGCN
  learning_rate: 0.0001
  weight_decay: 0.0001
  num_epochs: 200
  in_feats: 128
  hidden_feats: 512
  num_layers: 1
  batch_size: 8
  test_batch_size: 16
  valid_freq: 1
  early_stopping: 10
  eta_min: 0.00001
  save_freq: 10


MVCNN:
  project_name: BIMCompNet_MVCNN
  run_name: 'IfcNet-100'
  svcnn: 'vgg16'
  pretraining: True
  data_dir: 'H:\BIMCompNet'
  gpu_device: '0'
  # 'ArchShapesNet', 'Edges', 'Faces', 'IfcNet', 'Vertices'
  view_name: 'IfcNet'
  # "_sample_100", "_sample_500", "_sample_1000", "_sample_5000"
  sample: "sample_100"
  save_path: 'Q:\pychem_project\BIMCompNet\results\mvcnn_output\ifcnet\100'
  model_weights_path: 'Q:\pychem_project\BIMCompNet\results\mvcnn_output\ifcnet\test_100\f1_mvcnn_model.pth'
  learning_rate: 0.00001
  weight_decay: 0.0001
  eta_min: 0.000001
  momentum: 0.9
  num_views: 12
  batch_size: 8
  test_batch_size: 16
  num_epochs: 100
  dropout: 0.3
  early_stopping: 10
  valid_freq: 1


MESHNET:
  project_name: BIMCompNet_MESHNET
  run_name: 'MESHNET-5000'
  pretraining: True
  data_dir: 'H:\BIMCompNet'
  gpu_device: '0'
  max_faces: 500
  # "sample_100", "sample_500", "sample_1000", "sample_5000"
  sample: 'sample_5000'
  cache_dir: 'Q:\pychem_project\BIMCompNet\data\mesh_net_cache\c_5000'
  save_path: 'Q:\pychem_project\BIMCompNet\results\mesh_net_output\test_5000'
  model_weights_path: 'Q:\pychem_project\BIMCompNet\results\mesh_net_output\test_5000\f1_meshnet_model.pth'
  learning_rate: 0.0001
  weight_decay: 0.0001
  mask_ratio: 0.95
  mesh_convolution: 'Concat'
  eta_min: 0.00001
  momentum: 0.9
  batch_size: 8
  test_batch_size: 16
  num_epochs: 100
  dropout: 0.2
  early_stopping: 10
  valid_freq: 1
  seed: 95


VOXNET:
  project_name: BIMCompNet_VOXNET
  run_name: 'VOXNET-5000'
  data_dir: 'H:\BIMCompNet'
  gpu_device: '0'
  # "sample_100", "sample_500", "sample_1000", "sample_5000"
  sample: 'sample_5000'
  cache_dir: 'Q:\pychem_project\BIMCompNet\data\vox_net_cache\c_5000'
  save_path: 'Q:\pychem_project\BIMCompNet\results\vox_net_output\test_5000'
  model_weights_path: 'Q:\pychem_project\BIMCompNet\results\vox_net_output\test_5000\f1_voxnet_model.pth'
  learning_rate: 0.00001
  weight_decay: 0.0001
  eta_min: 0.000001
  momentum: 0.9
  batch_size: 8
  test_batch_size: 16
  num_epochs: 100
  dropout: 0.2
  early_stopping: 10
  valid_freq: 1


DGCNN:
  project_name: BIMCompNet_DGCNN
  run_name: 'DGCNN-5000'
  pretraining: True
  data_dir: 'H:\BIMCompNet'
  gpu_device: '0'
  emb_dims: 1024
  point_num: 2048
  k: 40
  # "sample_100", "sample_500", "sample_1000", "sample_5000"
  sample: 'sample_5000'
  cache_dir: 'Q:\pychem_project\BIMCompNet\data\dgcnn_cache\c_5000'
  save_path: 'Q:\pychem_project\BIMCompNet\results\dgcnn_output\test_5000'
  model_weights_path: 'Q:\pychem_project\BIMCompNet\results\dgcnn_output\test_5000\f1_dgcnn_model.pth'
  learning_rate: 0.00001
  weight_decay: 0.0001
  eta_min: 0.000001
  momentum: 0.9
  batch_size: 8
  test_batch_size: 16
  num_epochs: 100
  dropout: 0.2
  early_stopping: 10
  valid_freq: 1
  seed: 95